### ISSUE TITLE
Feature Request: show git commands and output

### ISSUE THREAD

**Issue by fklappan** [francescmm/GitQlient#103]
**Version** 1.1.0
**OS** Linux Manjaro (KDE)

A new (optional) view showing the used git commands and output would be nice. It could be used for learning purposes and trouble shooting on errors.

**Comment by francescmm** [comment]
Hi @fklappan,

Thanks for the request! This could be quite easy to do since all (or almost all) the git commands are log, so the information is there. I would only need to store it in runtime per repository.

**Comment by francescmm** [comment]
I'm moving this to v1.4.0 and I'll create an opt-in view marked as _Debug_ where I'll show more stuff in addition to this.

**Comment by francescmm** [comment]
I added more log messages since I finally decided that another widget just for "learning" purposes would overload the app with information for no gain. Having that widget would mean I need to keep track of the memory and cache and it's something out of the current scope.

The log messages have Trace level so the logger level would have to be decrease to see them. I've improved the phrasing and they throw the whole git command that is being called. The are proceeded by a Debug message, so it will be some context about what's going on. In most of the cases the Debug and Log message have the same text, but it could be that a GitQlient operation takes 2, 3 or even more git commands.

I hope you find it helpful! :smile:
