### ISSUE TITLE
Suggestion: show all changed files in diff-view

### ISSUE THREAD

**Issue by fklappan** [francescmm/GitQlient#105]
**Version** 1.1.0
**OS** Linux Manjaro (KDE)

**Actual behavior**
The "Diff" view is only available if I actively select a file to be diffed. If no file is double clicked (or added through the context menu), the diff view is disabled. Also I need to add every single file to the diff view.

**Suggested behavior**
At least my workflow is to always check every changed file for their specific changes before commiting them (thinking about the changes, looking for cleanup, etc.).

So the diff view should list all uncommited changed files without adding them explicitly to the view.
The icing on the cake would be the possibility to also stage the changes from within the diff view.

If you don't like the idea we could stage the already diffed files from the "diff" view with double click (to avoid the back and forth between the views).

**Additional information**
Coming from Windows Fork, the workflow with checking every diff before commit seems natural to me. I think this would be a gread addition to GitQlient from an UX point of view.

**Comment by francescmm** [comment]
Hi @fklappan,

I think that some of the features are [already in place](https://francescmm.github.io/GitQlient/#the-diff-view)!

To actually enter the Diff view you have several ways to go:
1. By double clicking on a specific commit in the graph view, it opens the diff with its parent. The same applies to the "local changes".
2. This also works (or should :stuck_out_tongue_closed_eyes:) if you select two commits in the graph view and select Diff in the context menu.

This action, in addition to the one you describe, it opens the diff view with the full commit view. In addition, you can double click the file name in the list shown in the bottom left part of the Diff view. When you do so, the new opening file will be shown in full file format.

Let me know if this solves or I'm misunderstanding something!

About the stage files from diff view: I think that's a good idea and I'm actually missing it myself. So let's see what can I do for 1.2.0!

**Bonus track:** Since you're asking about new things and UX experience... If you really want to freak out I'd suggest you try the last commit on _develop_ branch. It's what I'm using in production. It's really stable now and I'm going to code freeze it really really soon. I've added some improvements like "live edition" of the file :smiley:

**Comment by fklappan** [comment]
Ah ok, I admit I missed the double click in the graph view. Thanks! :) 
Maybe the diff view could be pimped a little (looks like a simple git diff output) but I guess it's fine and there are more urgent things to do.

Maybe I found a bug though (at least when commit from diff view is implemented): double click on the local changes from the graph view does not include new files in the diff. Is this intended (like "new file need no diff")?

So I think this issue could be closed. Thanks for your answer.

Regarding the bonus track: I'm having troubles compiling GitQlient with Qt 5.15. So first I need to get my environment back on track. But I definitely will "check it out"! (pun intended ;-) )

**Comment by francescmm** [comment]
Thanks for the feedback, @fklappan! And yes, I did to not have a diff for new files, since well... they're new. But I'm pretty sure I can change that if more people asks about it. I'm pretty sure that there's still a way to saw the file contents, though.

About Qt 5.15, yeah, I'm doing a quick test and there are several changes. Actually, one of the changes it's a "breaking change" since the function they are asking to use is not added in Qt5.14. I guess this is the preparation for Qt6. I've closed #106 so you should be able to pull and compile :)
