### ISSUE TITLE
Unable to start with a  fresh/empty repository

### ISSUE THREAD

**Issue by laurent-simon** [francescmm/GitQlient#108]
When you start with an empty repository ( `git init` and nothing else ), there is no way to add any file to it with GitQlient. The `Untracked files` list stays desperately empty (despite refreshes).

You have to go to the command line and use `git add` to add a first file (at least), then GitQlient becomes operational on the repository.

**Comment by francescmm** [comment]
Hi @laurent-simon,

Thanks for reporting this! This is clearly a bug. I'll fix it as soon as possible and release a path version.

**Comment by fklappan** [comment]
Can confirm with updated develop branch.

**Technical information**
Should be an easy fix for you @francescmm 

Take a look at 
* GitRequestorProcess.cpp at line 35
  If no output was captured, no history is being built. I simply removed the `ba.size()` part of the condition for testing, and it worked.

* RevisionsCache.cpp at line 201
  If no parent SHA is provided, the file will not be added to the `mRevisionsFileMap`. I tried a simple fix with 
  `
if (!sha1.isEmpty() && ( sha2.isEmpty() && mRevisionFilesMap.size() == 0))
   {
      // probably the first item in history of the repo
      mRevisionFilesMap.insert(key, file);
      return true;
   }
`

I'm pretty sure both of them are not "clean" solutions, but I don't know the codebase good enough yet to contribute real code.

Happy coding :smile:

**Comment by francescmm** [comment]
Hi @fklappan,

The first option would be better than the second one and I can actually explain why that worked so easily! :smile: 

It turns out that the problem is that no "work in progress" commit is added. The revisions/commits are added in the cache once the GitRequestorProcess emits the procDataReady signal. That drives to the GitRepoLoader::processRevision method and in there, all the revisions are added as well as the WIP commit (in the GitQlient _slang_).

I'm going to actually go for the first option. I actually thing it's a clean solution for the following reason: the signal should be triggered if the query went well. It's not a matter of GitRequestorProcess how much information the query reported. That should be handled by the GitRepoLoader::processRevision.

**Comment by francescmm** [comment]
I've published a [patch v1.1.1](https://github.com/francescmm/GitQlient/releases/tag/v1.1.1) with the fix.
