### ISSUE TITLE
Feature Request: subtree

### ISSUE THREAD

**Issue by hilpara** [francescmm/GitQlient#136]
Would it be possible to have subtrees supported?

**Comment by francescmm** [comment]
Hi @hilpara,

I can consider it for the version 1.3.0.

Do you know of a repo that uses that feature so I can test it?

**Comment by francescmm** [comment]
Hi @hilpara I've been doing a bit of research now and I see one big problem on the subtrees.

Subtrees are really nice to work with in the sense that you get the code right after a pull (obviously since it's just another remote). But what makes it difficult to work in a UI is that Git doesn't provide any way (by default) to list how many and which are the subtrees on a repo.

There are some hacks but that implies using Bash what is actually not supported in all platforms that GitQlient is present.

Do you have an idea about how you would like to see the subtree representation in GitQlient?

**Comment by hilpara** [comment]
Sourcetree is showing it like sub modules. I guess you have seen this tutorial https://www.atlassian.com/git/tutorials/git-subtree

**Comment by francescmm** [comment]
Yep, I check that and some other posts. I actually have a branch locally for GitQlient where I do the experiments, however I'm struggling on a good way of showing all subtrees.

It has been a long time since I use Sourcetree and I guess what they're doing is basically adding a script on top. The only problem in GitQlient is that I can solve the Windows part and the *nix part. But OSX will run with untested subtree (probably not even running them) since I don't have the means to test it.

We'll see how it goes.

**Comment by hilpara** [comment]
Sourcetree has its own configuration file inside .git folder and in there is:
subtree0.prefix=Folder/ModuleName
subtree0.path=/Path/to/git/repository.git
subtree0.refspec=master

And in GUI it will be shown like:
Subtree
---Folder
------ModuleName

**Comment by francescmm** [comment]
That was what I had in mind. But that only solves the listing when it is initialized from GitLQient.

But it wouldn't work when an already existing repository is opened later on with the app, right?

**Comment by hilpara** [comment]
I have never checked how the subtrees are handled in a sourcetree or in git generally. I guess they only "work" properly in a given software where they were added. So if you have existing repositories where there wasn't gitQclient.conf or what ever the name is, you have to add the subtrees manually again. But the gitQclient.conf has to be pushed to origin with the rest of the files, so that when somebody else checks your repository, the configuration files is also there not to miss the subtrees.

**Comment by hilpara** [comment]
There is also something on [stackoverflow](https://stackoverflow.com/questions/3202674/procedure-for-cloning-git-repos-that-use-subtree) .

**Comment by francescmm** [comment]
Hi @hilpara ! I'm happy to present you the subtree implementation, at least the first step!

In the near future I'll add the _merge_ since that involves taking care of conflicts.

**Comment by francescmm** [comment]
I've tested it with my own subtrees (not pushed) but it would be nice if you could checkout the branch and double check.

Otherwise I'll just merge it :)
