### ISSUE TITLE
Create HaikuPorts recipe to install via Package Manager on Haiku OS

### ISSUE THREAD

**Issue by cyrusbuilt** [francescmm/GitQlient#139]
Assuming #138 is merged in, would it be possible to create a recipe for HaikuPorts so that it can be installed via Haiku's Package Manager?

Documentation can be found here: [https://github.com/haikuports/haikuports/wiki](https://github.com/haikuports/haikuports/wiki).  Since I have a couple installations of Haiku, I would of course be willing to assist.

**Comment by francescmm** [comment]
Hi @cyrusbuilt for me it's fine to create/have a recipe although I can't do it myself because of lack of time. I'm already supporting the three major ones and even now, OSX is not yet "officially" tested.

I'm happy to support you and store the config files or whatever Haiku needs to be setup, as well as modifying the CI (or even adding a new one) for Haiku. I need, though, some that actually does the work of creating all those files and building the app, unless there is a guide "next, next, next" that I can follow from Ubuntu :smile: 

Would that work for you?

**Comment by cyrusbuilt** [comment]
Fair enough. I understand completely. I'll take a crack at it as soon as I digest all the haikuports documentation.

**Comment by cyrusbuilt** [comment]
That being said, good work! I tried the *one* other GUI for git on haiku that I could find and couldn't even get it to work correctly. GitQlient works flawlessly so far and is a fine piece of software.

**Comment by cyrusbuilt** [comment]
Just an update: I wrote a recipe for haikuports that includes that patch.  Just waiting for the PR to (hopefully) get merged and then it will be available in the HaikuDepot app for users to download and install.

The PR is here: [https://github.com/haikuports/haikuports/pull/5229](https://github.com/haikuports/haikuports/pull/5229)

**Comment by francescmm** [comment]
Thanks for the update @cyrusbuilt !

I was wondering what would happen for the future so it gets updated. My plan is to actually release 1.2.0 next Monday. I've checked the files and they point to the Release Candidate (1.2.0-rc). Do you think they needed to be updated?

**Comment by cyrusbuilt** [comment]
Yeah I'll create another PR or just bump the version in haikuports after 1.2.0 is released.  At this point, I'm just hoping to get my PR approved first, and get the RC into haikudepot, then update it later once 1.2.0 final is released.

**Comment by cyrusbuilt** [comment]
I'm happy to report my PR was just accepted!

**Comment by francescmm** [comment]
I'll close this issue, then! Thanks a lot for your help! :)
