### ISSUE TITLE
Added Qt 5.9.9 compatability, fixed git diff for files

### ISSUE THREAD

**Issue by speck0413** [francescmm/GitQlient#143]
**What current behavior doesn't fully fit your needs? Why?**
Couldn't compile against qt 5.9.9 code-base, needed for old pc's running RHEL 5.11 (don't ask).  Got everything compiled up to qt 5.9.9 and made some small tweaks to give compability.
Git Diff wasn't working when you double clicked on files.
old command: git diff -w -U15000 %1 %2 %3
new command: git diff -w -U15000 %1 %2 -- %3

**What you'd like to see? Propose a solution**
See attached zipped patchfile, not sure correct route for proposing this.

Great software, especially given low amount of dependencies.

[file_diff_fix_and_qt5.9.9_compat.patch.zip](https://github.com/francescmm/GitQlient/files/5185893/file_diff_fix_and_qt5.9.9_compat.patch.zip)

**Comment by francescmm** [comment]
Hi @speck0413 !

I've been reviewing the patch but I think it's a bit old nowadays. I've tried to make the code compatible but I would have to insert a lot of ifdefs to check the current Qt version. In some places the code gets a ugly and there are a lot of places where it complains.

Qt 5.9 was discontinued in May 2020 and the oldest LTS is 5.12. I'm aware that you probably won't be able to upgrade to 5.12, but I cannot maintain the code for such an old version (5.9) since even between minor version I'm seeing several breaking changes. Finally, even 5.12 is getting old and will stop being supported by the end of the next year.

I've just made a commit that will give support for **Qt 5.12** I hope you find it useful if you can upgrade your Qt version.

**Comment by speck0413** [comment]
ack I have created a fork I will maintain with 5.9.9 compatibility instead.
