### ISSUE TITLE
Configuration Via External File

### ISSUE THREAD

**Issue by speck0413** [francescmm/GitQlient#144]
Would be nice to have external files for configuring GUI
1) Location of GIT client if not in PATH
2) Settings at same level as GitQlient for defaults, to facilitate deployment for team

**Comment by francescmm** [comment]
Hi @speck0413,

I was reviewing your request, and I was wondering if you refer to the general GitQlient values or per repo. The general GitQlient config right now is the following one:

![image](https://user-images.githubusercontent.com/4884514/92996662-7a181500-f50d-11ea-8434-7188cf0cd66d.png)

In the version 1.2.0, one can configure several things for each repo. However, that doesn't make much more sense since it also stores user specific information like tokens and Git user related information.

If you confirm that is the general GitQlient config, I have no problems to add that.

**Comment by speck0413** [comment]
Yes general gitQlient config.  I'm attempting to deploy this across the team and am having to custom compile git and all support libs (openssl etc...) given we're forced into running an ancient redhat.  Ideally if I could set a custom path and specify the config location I would be able to deploy without having to make a complicated launcher command :).

**Comment by francescmm** [comment]
Cool! The changes I've made solve the issue although they're in a development branch. They will be available in 1.3.0.

If I have time, I'll check if I can do a patch with this changes and the support for Qt 5.9.
