### ISSUE TITLE
Doesn't respect desktop theme

### ISSUE THREAD

**Issue by luntik2012** [francescmm/GitQlient#195]
xfce, adapta gtk theme

![Screenshot_2021-02-14_14-29-44](https://user-images.githubusercontent.com/8270543/107875570-d70b6300-6ed1-11eb-9250-295d5405c9e9.png)

**Comment by francescmm** [comment]
Hi @luntik2012 ,

Right now desktop theme styles are not supported. Despite that the styles should be the same that the main UI has. After checking the code I've seen that they were not parsed, I hope this commit solve it :)

If you'd like to compile development branch that would be nice, otherwise I'll include this in 1.3.1.

Thanks for reporting!

**Comment by luntik2012** [comment]
the same with window header
![Screenshot_2021-02-14_15-13-40](https://user-images.githubusercontent.com/8270543/107876509-6e26e980-6ed7-11eb-9a3a-ff3c3bc0eb8d.png)

with "open file" dialog and many other places

![Screenshot_2021-02-14_15-16-06](https://user-images.githubusercontent.com/8270543/107876561-b8a86600-6ed7-11eb-9ff5-137cb63ffea5.png)
![Screenshot_2021-02-14_15-16-52](https://user-images.githubusercontent.com/8270543/107876574-d249ad80-6ed7-11eb-95c9-fa61f141bf23.png)
![Screenshot_2021-02-14_15-17-14](https://user-images.githubusercontent.com/8270543/107876580-e1306000-6ed7-11eb-910a-a6db69d92557.png)
![Screenshot_2021-02-14_15-18-01](https://user-images.githubusercontent.com/8270543/107876597-fc9b6b00-6ed7-11eb-9635-63d09d0494c2.png)

**Comment by francescmm** [comment]
Hi @luntik2012 , after reviewing the issues here I can say that this is a problem of Adapta theme. They should check what they're missing when they override the stylesheet.

GitQlient provides their own styles and they are the only officially supported. For your case I would say that the best fit it's the **Bright** style, although you might find some artifacts due to the integration.

Please, open a bug on the adapta gtk theme repository or backlog.

**Comment by luntik2012** [comment]
AFAIU you use your own style and the issue title is invalid, so my DE theme doesn't matter, but your theme is incomplete, app doesn't look consistent. For now I don't want to use this app, just reported after reading some release news.
