### ISSUE TITLE
[BUG] No installer provided for recent releases

### ISSUE THREAD

**Issue by auxym** [francescmm/GitQlient#221]
**Describe the bug**
The readme states that a windows installer is provided on the release page.

**To Reproduce**

**Expected behavior**
There is an installer available for v 1.4.0, but not for later versions.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Release version or SHA: 1.4.2 and 1.4.3
 - If manually compiled, compiler version: 

**Additional context**

**Comment by francescmm** [comment]
Hi @auxym,

I know it has passed a month since you opened the bug and I didn't realized before that those version where only fixes specially meant to solve the build of DEB packages for Linux and DMG for Apple.

There is no new feature that would benefit for Windows so I decided to skip them.

I'll release 1.5.0 for all platforms as usual.
