### ISSUE TITLE
Feature: Show the github/gitlab avatar of the user in the associated commit or PR/MR within the UI

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#226]
**Describe the solution you'd like**
It would be cool to have the option to see have the avatar of said user associated with the commit or PR to be shown in the details column of the commit and perhaps even the Author column.

**Describe alternatives you've considered**
n/a

**Additional context**
![gitqlient-avatar-feature](https://user-images.githubusercontent.com/4140247/146422293-a982cb22-4774-4c9f-b655-375e7b6d8a43.png)

**Comment by francescmm** [comment]
Hi @luzpaz, thanks for the suggestion!

I remember I consider this when I was starting to integrate the GitHub/GitLab API into GitQlient, however I didn't decide for it since it's kind of a network overload. I'll try to explain how GitQlient is architectured right now and why there exists such overload:

In GitQlient, the GitHub/GitLab integration is (almost) isolated from the rest of the app. The only place where you can see some integration right now is in the graph where in case a PR exists on a branch it will show an option in the context menu to open the PR in the browser. For any other option you would have to go to the integration UI screen.

As a consequence, the information of a specific commit doesn't contain anything related with the _username_ of the commit, rather than the information that Git provides. The commit contains public information such as the email, name, etc. but nothing of that is useful for GitHub or GitLab to identify a user.

For that reason I would need to query the GitHub/GitLab REST API with the SHA of the commit, get the _avatar URL_ from the user data and after that download it and store it locally. It would be nice to keep a cache so GitQlient avoids querying the API when it was done before.

It's more time consuming than complex (from my POV) but I'm still hesitant to introduce such dependency when my idea was to remove it from the graph since it wasn't feeling that comfortable.

I'll give it a thought during holidays.

**Comment by luzpaz** [comment]
Thanks for the detailed explanation. It is appreciated! Have a happy holiday!
