### ISSUE TITLE
Feature: Right click context dialog has an option to Open with... (preferred IDE)

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#232]
Since the bundled code editor is bare-bones, it would be nice to have an option to utilize ones favorite IDE when a file within a commit is chosen.

**Additional context**
![image](https://user-images.githubusercontent.com/4140247/147689920-263264f3-7b63-43e3-bca5-8df764d66a2d.png)

**Comment by francescmm** [comment]
Hi @luzpaz I was thinking about this feature you requested and I have several questions:

1. When you want to open a file with and IDE, do you mean a modified file in the WIP commit, or in _any_ commit you select in the tree?
2. If you mean **any** commit of the tree, what would be the purpose of that considering that the file could be completely obsolete?
3. Another option that comes to my mind is that instead of opening the file, you mean opening the diff of the file vs it's older commit. Is that what you mean ("Open **diff** with...")? It sounds a bit strange, though.

Let me know what you were thinking so I can further analyse if it fits in GitQlient.

**Comment by luzpaz** [comment]
1. Former. But it would be nice to have the ability to open any file selected in the tree (but not necessarily referencing a historic commit)  
2. Well, for efficiency reasons - it would be a fast way to open the file.
3.  No, I don't mean ('Open diff')

Thanks for the follow-up :smile:

**Comment by francescmm** [comment]
I see that we have a nice "File System view" in the Blame widget. So I could perfectly use that for this option, considering that you have all the files in the repo in there.

Would that be an option?

I can think of adding an **additional** option to open the file in the WIP widget. Although I'm still thinking about this since it could be confusing since:

1. If the option is in the GitQlientPlugin, it would open the file directly in QtCreator.
2. If the option is in the GitQlient app, it would allow you to choose the IDE.

May be is not confusing if both options are different enough. I'll think about it :)

**Comment by luzpaz** [comment]
It would be nice to have several options actually (in GitQlient app):
1. Preference that lets you choose your default IDE
2. In the RMB context menu have an `Open with...` option
3. In the RMB context menu have an 'Open with $prefered_ide_name' option

**Comment by francescmm** [comment]
> It would be nice to have several options actually (in GitQlient app):
> 
> 1. In the Preference panel, have an option that lets you choose your default IDE
> 2. In the RMB context menu have an `Open with...` option
> 3. In the RMB context menu have an 'Open with $prefered_ide_name' option

For clarity, I think I'll add only an option named "Open with external editor". This option would be disabled unless the user provides one in the Preference panel.

Originally GitQlient was meant to be just a plugin for QtCreator but this has grown a lot, so now it's easier to have it as an independent app. However, I understand that people may want to edit "merge" conflicts and that's why I added the small "editor" feature to it.

I'm aware that the GitQlient editor isn't as complete as a real IDE is, so that's why I'll add this but only for the app. In the GitQlientPlugin (only available for QtCreator for obvious reasons) it will open the file in the editor.

By default, though, there won't be any IDE set, and the user must know what params the IDE requires, just setting the name of the IDE might not work.

Finally, since this has the complexity of executing a task outside GitQlient and interacting with the OS, I won't give it the highest prio, mainly because there's always the workaround of copying the path of the file and later on to open it in the IDE manually :smile:

**Comment by francescmm** [comment]
@luzpaz after these two commits, you can configure the IDE you want to open the files with, and use it in the "unstaged menu" of the WIP UI, and also in the File System view in the Blame widget.
