### ISSUE TITLE
about subversion operation

### ISSUE THREAD

**Issue by FunningC0217** [francescmm/GitQlient#242]
see https://git-scm.com/docs/git-svn

GitQlient is very easy to use, but the current git operation supports seamless switching and use of SVN warehouses.
Does GitQlient currently support this operation?
If it is not supported now, is there any idea of relevant function implementation.
This is just my personal idea.

Thanks.

**Comment by francescmm** [comment]
Hi @FunningC0217 I haven't consider it and I would have to personally use it to make sure I cover it perfectly.

GitQlient code is organized in a way that it would be relatively easy to inject a SVN implementation instead of Git (although I'm aware is not the exact same thing you're asking). But for now I'm focused in providing the best UI/UX with the functionality from Git.

May be in a near future after #77 I could consider this. But, if you feel brave to jump into the code and contribute, don't hesitate to ask me any doubts you have! :)
