### ISSUE TITLE
Improve RMB context `git reset` option by providing succint descriptions of what each one does within contex dialog

### ISSUE THREAD

**Issue by luzpaz** [francescmm/GitQlient#243]
**What current behavior doesn't fully fit your needs? Why?**
![Screenshot_20220402_122846](https://user-images.githubusercontent.com/4140247/161392276-7ea48366-765f-4532-9a79-ab28e0ef62f2.png)
The UI could be a little more generous 

**What you'd like to see? Propose a solution**
![Screenshot_20220402_122846-1](https://user-images.githubusercontent.com/4140247/161392448-1426cbbb-ce8d-427c-8819-d985167e6541.png)

**Describe alternatives you've considered**
Leave it up to the user to look up `git reset` manual

**Comment by francescmm** [comment]
As I'm commenting in #245, I think it's best if the user knows what these commands mean. I can add that description as a tooltip and even inside parenthesis. The problem of sudden changes in this menus is that current users might find it hard to know what is what.

I'll _add_ the description instead of replacing it. Users will learn faster that way, I believe.
