### ISSUE TITLE
Git GPG signing on request

### ISSUE THREAD

**Issue by sapphirepro** [francescmm/GitQlient#280]
It must ask what GPG key to use to sign repository, otherwise in many cases it's simply useless
**Improvement request** template.

**Describe the solution you'd like**
Request GPG key list and offer signing options, if nothing configured

**Describe alternatives you've considered**
Request GPG key list and offer signing options, if nothing configured, like does GitKraken or CLion and other JEtBrains software

**Comment by francescmm** [comment]
Hi @sapphirepro,

Unfortunately this is not technically possible. Both GitKraken and CLion uses libgit2 to handle both the connectivity and the command execution. This has some benefits (i. e. it's easier to customize the experience), but also some drawbacks (complex change for GitQlient to implement, manually building and linking OpenSSH and OpenSSL).

Right now I won't implement this because despite GitQlient architecture is planned to allow such use of libgit2, it would require a deep change in the building and linking process.
