### ISSUE TITLE
Actions that change the state of repository should be more verbose

### ISSUE THREAD

**Issue by mslusarz** [francescmm/GitQlient#84]
I would like to see first what "Pull" & "Push" will do before actually performing such action.

**Comment by francescmm** [comment]
Hi, thanks for the suggestion!

For the push I could add a _dry-run_ option, but what would you like to see in the pull exactly?

**Comment by mslusarz** [comment]
I would like to know from which remote and from which branch the pull is going to import commits and stop it if anything other than fast-forwarding will be performed.

That's why I never use "git pull" myself. I always do git fetch on a remote I want to take changes from, verify I don't have any commits locally with git log, and then do git reset --hard on the fetched branch.

**Comment by francescmm** [comment]
I actually see this as part of a major feature. Nowadays the support for multiple remotes it's quite vague. I think this is an area that could be expanded and improved with lots of new features.

I'll try to come up with a planning for big features soon.

**Comment by francescmm** [comment]
Hi @mslusarz I've been investigating the options and I saw that you could fetch a remote (fixed now in develop) and then diff that branch and the one you want to merge in.

Since Git doesn't have a dry-run option for pull and the "reset --hard" option it's already available.

I'd ask you that if you find a missing option in GitQlient open a new ticket for it!
